# Example: ProductCategory with name filter

feature_name: ProductCategory

# Solution root directory. Override with -s on CLI.
solution_dir: C:\Work\TPOSAPP

domain_shared_model_folder: "Models\\Products"

upsert_properties:
  - ["string", "Name", "true", ""]
  - ["string", "Code", "false", "string.Empty"]

dto_properties:
  - ["long", "Id", "true", ""]
  - ["string", "Name", "true", ""]
  - ["string", "Code", "true", ""]

get_all_filters:
  - ["string?", "name", "FromQuery"]

dry_run: false
